dev:
  STACK_NAME_PREFIX: tz-
  VPC_ID: # TODO
  SUBNET_ONE_ID: # TODO id not arn
  SUBNET_TWO_ID: # TODO id not arn
  CERTIFICATE_ARN: # TODO 
  CERTIFICATE_ARN_FOR_CLOUDFRONT: # TODO # has to be in us-east-1 :P
  DOMAIN: # TODO
  HOSTED_ZONE_ID_DOMAIN: # TODO

  CACHE_POLICY_DEFAULT_TTL: 0
  CACHE_POLICY_MAX_TTL: 3600
  CACHE_POLICY_MIN_TTL: 0

  APPLICATION_IMAGE: timothypage/container-info
  APPLICATION_PORT: 9292
  APPLICATION_CPU: 1024
  APPLICATION_MEMORY: 2048
  APPLICATION_HEALTHCECK_GRACE_PERIOD: 300

